name: CI Pimcore

on:
    pull_request:
        branches: [ main, develop ]
    schedule:
        - cron: "0 0 * * *"

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    pimcore:
        runs-on: ubuntu-latest
        env:
            PIMCORE_IMAGE: docker.io/pimcore/pimcore:php8.3-latest
            PIMCORE_PACKAGE: pimcore/skeleton:^v2024.4
            COMPOSER_HOME: /tmp/composer
            COMPOSER_CACHE_DIR: /tmp/composer-cache
            PIMCORE_VERSION: "11.5.*"
        name: Bundle Check
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Pull Pimcore image
                run: |
                    set -ex
                    docker pull ${PIMCORE_IMAGE}

            -   name: Create Pimcore project
                run: |
                    set -ex
                    echo "Using demo_package=${PIMCORE_PACKAGE}"
                    docker run \
                      -e COMPOSER_HOME=${COMPOSER_HOME} \
                      -e COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR} \
                      --volume=${{ github.workspace }}/:/var/www/html \
                      --workdir=/var/www/html \
                      --user=$(id -u):$(id -g) \
                      ${PIMCORE_IMAGE} \
                        composer create-project \
                        ${PIMCORE_PACKAGE} \
                        --no-install \
                        --no-scripts \
                        --no-interaction \
                        sample-project
                    docker run \
                      -e COMPOSER_HOME=${COMPOSER_HOME} \
                      -e COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR} \
                      -e PIMCORE_VERSION=${PIMCORE_VERSION} \
                      --volume=${{ github.workspace }}/:/var/www/html \
                      --workdir=/var/www/html/sample-project \
                      --user=$(id -u):$(id -g) \
                      ${PIMCORE_IMAGE} \
                        bash -lc 'composer remove pimcore/platform-version --no-update --no-interaction \
                        && composer require pimcore/pimcore:"${PIMCORE_VERSION}" --no-update --no-interaction \
                        && composer update --no-scripts --no-interaction'

            -   name: Docker and Database Setup
                run: |
                    set -ex
                    cd sample-project/
                    docker compose -f docker-compose.yaml config

                    docker compose pull --quiet
                    docker compose down -v --remove-orphans
                    docker compose -f docker-compose.yaml up -d

                    docker compose exec -T -- php bash -c '\
                    curl -sfL https://github.com/powerman/dockerize/releases/download/v0.11.5/dockerize-`uname -s`-`uname -m` \
                    | install /dev/stdin /usr/local/bin/dockerize'

                    docker compose exec -T -- php dockerize -wait tcp://db:3306 -timeout 5m

            -   name: Install Pimcore
                run: |
                    set -ex
                    cd sample-project/

                    docker compose exec -T --workdir /var/www/html php composer install --no-scripts --no-interaction
                    
                    docker compose exec -T --workdir /var/www/html \
                        php vendor/bin/pimcore-install \
                        --mysql-host-socket=db \
                        --mysql-username=pimcore \
                        --mysql-password=pimcore \
                        --mysql-database=pimcore \
                        --admin-username=admin \
                        --admin-password=admin \
                        -n

                    docker compose exec -T --workdir /var/www/html \
                        -e DATABASE_URL=mysql://pimcore:pimcore@db:3306/pimcore \
                        php bin/console assets:install --symlink --relative
                    
                    docker compose exec -T --workdir /var/www/html php php -v

            -   name: Install bundle
                run: |
                    set -ex
                    cd sample-project/
                    docker compose exec -T --workdir /var/www/html php composer require dennispansegrau/pimcore-content-migration-bundle:dev-develop

            -   name: Install bundle dependencies
                run: |
                    set -ex
                    cd sample-project/
                    docker compose exec -T --workdir /var/www/html/vendor/dennispansegrau/pimcore-content-migration-bundle php \
                        bash -lc 'composer install --no-interaction --prefer-dist;'

            -   name: PHPStan Test
                run: |
                    set -ex
                    cd sample-project/
                    docker compose exec -T --workdir /var/www/html/vendor/dennispansegrau/pimcore-content-migration-bundle php \
                        bash -lc 'composer phpstan'

            -   name: CS Test
                run: |
                    set -ex
                    cd sample-project/
                    docker compose exec -T --workdir /var/www/html/vendor/dennispansegrau/pimcore-content-migration-bundle php \
                        bash -lc 'composer cs'

            -   name: PHPUnit Tests
                run: |
                    set -ex
                    cd sample-project/
                    docker compose exec -T --workdir /var/www/html/vendor/dennispansegrau/pimcore-content-migration-bundle php \
                        bash -lc 'composer test'

            -   name: Compose down
                if: always()
                run: |
                    cd sample-project/
                    docker compose down -v --remove-orphans
